site_name: Documentation Programming Quotes MNSJ

nav:
  - Home: index.md
  - User's Guide:
      - Features: features.md
      - Core Functions: functions.md
      - User Interface: user-interface.md
  - Logs:
      - Initiateur: logs/log-initiateur.md
      - Contributeur 1: logs/log-contributor1.md
      - Contributeur 2: logs/log-contributor2.md
      - Contributeur 3: logs/log-contributor3.md

theme: readthedocs
